from typing import Any


def _safe_div(a: float, b: float, default: float = 0.0) -> float:
    return round(a / b, 4) if b else default


def calculate_ratios(balance_sheet: dict[str, Any], income_statement: dict[str, Any],
                      cash_flow: dict[str, Any]) -> dict[str, float]:
    bs, inc = balance_sheet, income_statement

    current_assets = bs.get("current_assets", 0)
    current_liabilities = bs.get("current_liabilities", 0) or 1
    inventory = bs.get("inventory", 0)
    cash = bs.get("cash", 0)
    total_assets = bs.get("total_assets", 0) or 1
    total_debt = bs.get("total_debt", 0)
    total_equity = bs.get("total_equity", 0) or 1

    revenue = inc.get("revenue", 0) or 1
    ebitda = inc.get("ebitda", 0)
    net_income = inc.get("net_income", 0)

    current_ratio = _safe_div(current_assets, current_liabilities)
    quick_ratio = _safe_div(current_assets - inventory, current_liabilities)
    cash_ratio = _safe_div(cash, current_liabilities)
    roe = round(_safe_div(net_income, total_equity) * 100, 2)
    roa = round(_safe_div(net_income, total_assets) * 100, 2)
    ebitda_margin = round(_safe_div(ebitda, revenue) * 100, 2)
    de_ratio = _safe_div(total_debt, total_equity)

    return {
        "current_ratio": round(current_ratio, 2),
        "quick_ratio": round(quick_ratio, 2),
        "cash_ratio": round(cash_ratio, 2),
        "roe": roe,
        "roa": roa,
        "ebitda_margin": ebitda_margin,
        "de_ratio": round(de_ratio, 2),
    }


def score_financial_health(ratios: dict[str, float]) -> dict[str, Any]:
    """Weighted deterministic scoring, 0-100."""
    liquidity_score = min(100, ratios["current_ratio"] * 35)
    profitability_score = min(100, max(0, ratios["ebitda_margin"] * 3))
    leverage_score = max(0, 100 - ratios["de_ratio"] * 60)
    returns_score = min(100, max(0, (ratios["roe"] + ratios["roa"]) * 1.8))

    score = round(
        0.3 * liquidity_score + 0.3 * profitability_score +
        0.25 * leverage_score + 0.15 * returns_score, 1
    )
    score = max(0, min(100, score))

    if score >= 75:
        category = "Healthy"
    elif score >= 55:
        category = "Stable"
    elif score >= 35:
        category = "Watch"
    else:
        category = "Distressed"

    return {"score": score, "category": category}


def generate_company_dna(ratios: dict[str, float], balance_sheet: dict[str, Any],
                          sector: str) -> dict[str, Any]:
    """Deterministic — never generated by an LLM, per design philosophy."""
    total_assets = balance_sheet.get("total_assets", 0) or 1
    fixed_assets_ratio = 1 - _safe_div(balance_sheet.get("current_assets", 0), total_assets)

    capital_intensity = "High" if fixed_assets_ratio > 0.55 else "Medium" if fixed_assets_ratio > 0.35 else "Low"

    capital_intensive_sectors = {"Manufacturing", "Steel", "Cement", "Oil & Gas", "Utilities"}
    pricing_power = "Low" if sector in capital_intensive_sectors and ratios["ebitda_margin"] < 15 else \
        "High" if ratios["ebitda_margin"] > 25 else "Medium"

    inflation_sensitivity = "High" if sector in capital_intensive_sectors else \
        "Medium" if ratios["de_ratio"] > 0.6 else "Low"

    cash_rich = ratios["cash_ratio"] > 0.5
    debt_heavy = ratios["de_ratio"] > 1.0

    if ratios["roe"] > 20 and ratios["ebitda_margin"] > 20:
        growth_stage = "Growth"
    elif ratios["roe"] > 8:
        growth_stage = "Mature"
    else:
        growth_stage = "Early / Turnaround"

    working_capital = "Efficient" if ratios["current_ratio"] >= 1.2 else "Constrained"

    return {
        "capital_intensity": capital_intensity,
        "pricing_power": pricing_power,
        "inflation_sensitivity": inflation_sensitivity,
        "working_capital": working_capital,
        "growth_stage": growth_stage,
        "cash_rich": cash_rich,
        "debt_heavy": debt_heavy,
    }
