"""Render Phase 1 results (audits, comparison, build, validation) to Markdown.

Kept separate from the analysis modules so presentation never contaminates the
computed numbers. Everything rendered here comes straight from the structured
report dicts produced by the auditor/comparator/builder/validator.
"""
from __future__ import annotations

from typing import Any


def _h(level: int, text: str) -> str:
    return f"{'#' * level} {text}\n"


def _bool(v: bool) -> str:
    return "✅ PASS" if v else "❌ FAIL"


def render_full_report(
    audits: dict[str, dict[str, Any]],
    comparison: dict[str, Any],
    build_decisions: dict[str, Any],
    validation: dict[str, Any],
) -> str:
    parts: list[str] = []
    parts.append(_h(1, "MacroRisk AI — Phase 1 Data Discovery & Canonical Dataset Audit"))
    parts.append(
        "_Generated by the Phase 1 pipeline. Every figure below is computed "
        "directly from the source files; no values were assumed or fabricated._\n"
    )

    parts.append(_render_toc())
    for name, audit in audits.items():
        parts.append(_render_dataset_audit(audit))
    parts.append(_render_comparison(comparison))
    parts.append(_render_build(build_decisions))
    parts.append(_render_validation(validation))
    parts.append(_render_conclusion(comparison, build_decisions, validation))
    return "\n".join(parts)


def _render_toc() -> str:
    return (
        "## Contents\n"
        "1. Per-dataset audit (STEP 1)\n"
        "2. Dataset comparison & merge recommendation (STEP 2)\n"
        "3. Master dataset construction (STEP 3)\n"
        "4. Master dataset validation (STEP 4)\n"
        "5. Decisions & conclusion\n"
    )


def _render_dataset_audit(a: dict[str, Any]) -> str:
    o = a["overview"]
    p = []
    p.append(_h(2, f"1. Audit — `{a['dataset']}`  (`{a['source_file']}`, {a['file_format'].upper()})"))
    p.append(f"- **Shape:** {a['shape']['rows']} rows × {a['shape']['columns']} columns")
    p.append(f"- **Observations:** {o['total_observations']}")
    p.append(f"- **Companies:** {o['n_companies']} — {', '.join(o['companies'])}")
    p.append(f"- **Sectors:** {o['n_sectors']} — {', '.join(o['sectors'])}")
    p.append(f"- **Distinct quarters:** {o['n_distinct_quarters']}")
    p.append(f"- **Quarter coverage:** {', '.join(o['quarter_coverage'])}")
    p.append(f"- **Time span:** {o['time_span']['start']} → {o['time_span']['end']}")
    if a["renamed_columns"]:
        renames = ", ".join(f"`{k}`→`{v}`" for k, v in a["renamed_columns"].items())
        p.append(f"- **Header normalization:** {renames}")
    p.append("")

    # Missing & duplicates
    mv, du = a["missing_values"], a["duplicates"]
    p.append(_h(3, "Data integrity"))
    p.append(f"- Missing cells: **{mv['total_missing_cells']}** "
             f"(rows with any missing: {mv['rows_with_any_missing']})")
    p.append(f"- Full-row duplicates: **{du['full_row_duplicates']}**")
    p.append(f"- Duplicate company-quarter records: **{du['duplicate_company_quarter_records']}**")
    p.append("")

    # Panel structure
    pb, qc = a["panel_balance"], a["quarterly_continuity"]
    p.append(_h(3, "Panel structure"))
    p.append(f"- Panel balanced: **{pb['is_balanced']}** "
             f"(quarters/company: {pb['min_quarters']}–{pb['max_quarters']})")
    p.append(f"- Quarterly continuity (no gaps): **{qc['is_continuous']}** "
             f"({qc['companies_with_issues']} companies with issues)")
    p.append("")

    # Descriptive stats table (compact)
    p.append(_h(3, "Descriptive statistics (numeric features)"))
    p.append("| Feature | mean | std | min | median | max | skew |")
    p.append("|---|--:|--:|--:|--:|--:|--:|")
    dist = a["distributions"]
    for col, d in dist.items():
        p.append(
            f"| {col} | {_f(d['mean'])} | {_f(d['std'])} | {_f(d['min'])} | "
            f"{_f(d['p50'])} | {_f(d['max'])} | {_f(d['skew'])} |"
        )
    p.append("")

    # Outliers
    out = a["outliers"]
    total_out = out.get("_total_outlier_cells", 0)
    p.append(_h(3, "Outliers (IQR, 1.5× fence)"))
    p.append(f"- Total outlier cells across numeric features: **{total_out}**")
    flagged = {c: v["count"] for c, v in out.items() if isinstance(v, dict) and v["count"] > 0}
    if flagged:
        p.append("- Per feature: " + ", ".join(f"{c}={n}" for c, n in flagged.items()))
    p.append("")

    # Correlation / multicollinearity
    corr = a["correlation_matrix"]
    vif = a["multicollinearity"]
    p.append(_h(3, "Correlation & multicollinearity"))
    if corr["high_correlation_pairs"]:
        pairs = "; ".join(
            f"{pr['a']}~{pr['b']} (r={_f(pr['r'])})" for pr in corr["high_correlation_pairs"][:8]
        )
        p.append(f"- Highly correlated pairs (|r|≥0.9): {pairs}")
    else:
        p.append("- No feature pairs with |r|≥0.9.")
    if vif.get("severe_features"):
        sev = ", ".join(f"{c}={_f(v)}" for c, v in vif["severe_features"].items())
        p.append(f"- Severe multicollinearity (VIF≥10): {sev}")
    else:
        p.append("- No severe multicollinearity flagged (all VIF < 10).")
    p.append("")

    # Accounting consistency
    ac = a["accounting_consistency"]
    p.append(_h(3, "Accounting consistency"))
    p.append("| Identity | % rows satisfied | violations | max rel. diff |")
    p.append("|---|--:|--:|--:|")
    for name, r in ac.items():
        p.append(f"| {r['formula']} | {r['pct_satisfied']}% | {r['rows_violated']} | {_f(r['max_relative_diff'])} |")
    p.append("")
    return "\n".join(p)


def _render_comparison(c: dict[str, Any]) -> str:
    p = []
    p.append(_h(2, "2. Dataset Comparison & Merge Recommendation (STEP 2)"))
    rel = c["relationship"]
    p.append(f"- **Relationship:** `{rel['label']}` — {rel['description']}")
    sd = c["schema_differences"]
    p.append(f"- **Raw headers identical:** {sd['raw_headers_identical']}; "
             f"**canonical schema identical:** {sd['canonical_columns_identical']}")
    if sd.get("note"):
        p.append(f"  - {sd['note']}")
    dt = c["datatype_differences"]
    p.append(f"- **Datatype differences:** {'none' if dt['identical'] else dt['differing_columns']}")
    ko = c["key_overlap"]
    p.append(f"- **Key overlap:** {ko['n_shared_keys']} shared, "
             f"{ko['n_only_in_a']} only in {c['datasets'][0]}, "
             f"{ko['n_only_in_b']} only in {c['datasets'][1]}")
    vc = c["value_conflicts"]
    if "pct_conflicting" in vc:
        p.append(f"- **Value conflicts on shared keys:** {vc['conflicting_rows']}/{vc['shared_keys']} "
                 f"rows ({vc['pct_conflicting']}%) disagree beyond tolerance; "
                 f"{vc['identical_rows']} identical")
        if vc.get("example_conflicts"):
            ex = vc["example_conflicts"][0]
            p.append(f"  - Example: `{ex['key']}` {ex['column']} "
                     f"{ex['value_a']} vs {ex['value_b']} (Δ={ex['relative_diff']})")
    rec = c["recommended_merge_strategy"]
    p.append("")
    p.append(_h(3, "Recommended merge strategy"))
    p.append(f"- **Recommended:** `{rec['recommended']}`  |  **Configured:** `{rec['configured']}`  "
             f"|  match: {rec['matches_config']}")
    p.append(f"- **Rationale:** {rec['rationale']}")
    p.append(f"- ⚠️ {rec['warning']}")
    p.append("")
    return "\n".join(p)


def _render_build(d: dict[str, Any]) -> str:
    p = []
    p.append(_h(2, "3. Master Dataset Construction (STEP 3)"))
    p.append(f"- **Strategy applied:** `{d['strategy']}`")
    p.append(f"- {d.get('strategy_detail', '')}")
    p.append(f"- Exact duplicate rows removed: **{d.get('exact_duplicate_rows_removed', 0)}**")
    if "company_quarters_with_conflicts_collapsed" in d:
        p.append(f"- Company-quarters with conflicts collapsed: "
                 f"**{d['company_quarters_with_conflicts_collapsed']}**")
    if d.get("duplicate_full_key_rows") is not None:
        p.append(f"- Duplicate rows on full provenance key: **{d['duplicate_full_key_rows']}**")
    macro = d.get("macroeconomic_columns_present", [])
    p.append(f"- **Macroeconomic columns present in sources:** "
             f"{macro if macro else 'none (datasets contain only company financials)'}")
    p.append(f"- Sorted by: {d.get('sorted_by')}")
    p.append(f"- **Final master shape:** {d['final_rows']} rows × {len(d['final_columns'])} columns")
    p.append(f"- Columns: {', '.join(f'`{c}`' for c in d['final_columns'])}")
    p.append("")
    return "\n".join(p)


def _render_validation(v: dict[str, Any]) -> str:
    p = []
    p.append(_h(2, "4. Master Dataset Validation (STEP 4)"))
    p.append(f"- **Effective panel key:** {v['effective_panel_key']}")
    p.append(f"- **Overall:** {_bool(v['all_checks_passed'])}\n")
    checks = v["checks"]
    p.append("| Check | Result | Detail |")
    p.append("|---|:--:|---|")
    p.append(f"| No duplicate company-quarter | {_bool(checks['no_duplicate_company_quarter']['passed'])} | "
             f"effective-key dupes: {checks['no_duplicate_company_quarter']['duplicates_on_effective_key']} |")
    p.append(f"| Correct quarterly ordering | {_bool(checks['correct_quarterly_ordering']['passed'])} | "
             f"unordered groups: {len(checks['correct_quarterly_ordering']['unordered_groups'])} |")
    p.append(f"| No broken accounting identities | {_bool(checks['no_broken_accounting_identities']['passed'])} | "
             f"see per-identity health |")
    p.append(f"| Correct datatypes | {_bool(checks['correct_datatypes']['passed'])} | "
             f"wrong: {checks['correct_datatypes']['wrong_dtype_columns'] or 'none'} |")
    p.append(f"| No obvious leakage | {_bool(checks['no_obvious_leakage']['passed'])} | "
             f"zero-var: {checks['no_obvious_leakage']['zero_variance_columns'] or 'none'}; "
             f"suspicious names: {checks['no_obvious_leakage']['suspicious_forward_looking_columns'] or 'none'} |")
    p.append("")

    # Informational notes
    dup_info = checks["no_duplicate_company_quarter"].get("info")
    if dup_info:
        p.append(f"> **Note (duplicates):** {dup_info}")
    acc = checks["no_broken_accounting_identities"]
    p.append(f"> **Note (accounting):** {acc['note']}")
    p.append("")
    p.append("Per-identity health on master:")
    p.append("| Identity | % satisfied | violations |")
    p.append("|---|--:|--:|")
    for name, r in acc["identities"].items():
        p.append(f"| {r['formula']} | {r['pct_satisfied']}% | {r['rows_violated']} |")
    leak = checks["no_obvious_leakage"]
    if leak.get("value_identical_column_pairs"):
        p.append("")
        p.append(f"> **Advisory (redundant columns):** value-identical pairs "
                 f"{leak['value_identical_column_pairs']} — {leak['note']}")
    p.append("")
    return "\n".join(p)


def _render_conclusion(comparison, build, validation) -> str:
    p = []
    p.append(_h(2, "5. Decisions & Conclusion"))
    rec = comparison["recommended_merge_strategy"]
    p.append(f"1. **Format detection:** both inputs detected and read successfully.")
    p.append(f"2. **Schema:** raw headers differed only by unit suffixes; normalized to one canonical schema.")
    p.append(f"3. **Relationship:** datasets are `{comparison['relationship']['label']}`.")
    p.append(f"4. **Merge strategy:** applied `{build['strategy']}` — {rec['rationale']}")
    p.append(f"5. **Master dataset:** {build['final_rows']} rows written to `master_quarterly_dataset.csv`.")
    p.append(f"6. **Validation:** {_bool(validation['all_checks_passed'])} on the effective panel key "
             f"{validation['effective_panel_key']}.")
    p.append("")
    p.append("**Phase 1 complete. No synthetic data generated and no models trained.**")
    p.append("")
    return "\n".join(p)


def _f(v: Any) -> str:
    if v is None:
        return "—"
    if isinstance(v, str):
        return v
    try:
        return f"{float(v):,.2f}"
    except (TypeError, ValueError):
        return str(v)
